Repository LLK/scratch-audio, pull requests merged in 2018-06, with the labels that each got.

#83 break up index.js into files per class
  src/AudioEngine.js
  src/AudioPlayer.js
  src/Loudness.js
  src/index.js
Labels: pr - needs review

#84 extend existing effects from Effect
  package.json
  src/AudioEngine.js
  src/AudioPlayer.js
  src/effects/Effect.js
  src/effects/PanEffect.js
  src/effects/PitchEffect.js
Labels: pr - needs review

#85 add and use VolumeEffect in AudioPlayer
  src/AudioPlayer.js
  src/effects/Effect.js
  src/effects/PanEffect.js
  src/effects/VolumeEffect.js
Labels: pr - needs review

#86 Test for effect
  .travis.yml
  package.json
  src/effects/Effect.js
  src/effects/PanEffect.js
  src/effects/VolumeEffect.js
  test/__mocks__/AudioContext.js
  test/__mocks__/AudioEngine.js
  test/__mocks__/AudioNode.js
  test/__mocks__/AudioParam.js
  test/__mocks__/AudioTarget.js
  test/effects/EffectShape.js
Labels: pr - good to merge

#88 Green SoundPlayer
  src/AudioEngine.js
  src/GreenPlayer.js
  src/effects/Effect.js
  src/effects/PanEffect.js
  src/effects/VolumeEffect.js
Labels: pr - needs review

#90 Release with build stages
  .travis.yml
  package.json
Labels: pr - good to merge

#91 Don't use npm prepublish
  .travis.yml
  package.json
Labels: pr - good to merge

#89 Green audio player
  src/AudioPlayer.js
  src/GreenPlayer.js
Labels: pr - needs review

#95 Tests for GreenPlayer
  package.json
  src/AudioEngine.js
  src/GreenPlayer.js
  src/StartAudioContext.js
  src/effects/Effect.js
  src/effects/VolumeEffect.js
  test/AudioEngine.js
  test/SoundPlayer.js
  test/__mocks__/AudioParam.js
Labels: pr - needs review

#92 SoundBank
  src/AudioEngine.js
  src/AudioPlayer.js
  src/GreenPlayer.js
  src/SoundBank.js
  src/SoundPlayer.js
  src/effects/Effect.js
  src/effects/EffectChain.js
  src/effects/PanEffect.js
  src/effects/PitchEffect.js
  src/effects/VolumeEffect.js
Labels: pr - needs work

#99 add missing docs: SoundPlayer, AudioEngine, Effect.name
  src/AudioEngine.js
  src/SoundPlayer.js
  src/effects/PanEffect.js
  src/effects/PitchEffect.js
  src/effects/VolumeEffect.js
Labels: pr - good to merge

#101 schedule stop DECAY in the future for firefox
  src/AudioEngine.js
  src/SoundPlayer.js
  src/effects/Effect.js
  src/effects/PanEffect.js
  src/effects/VolumeEffect.js
  test/SoundPlayer.js
Labels: pr - needs review
